mybatis-plus:
  configuration:
    cache-enabled: false # 关闭二级缓存
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

spring:
  messages:
    basename: i18n/error/message,i18n/error/description,i18n/error/solution
  datasource:
    url: jdbc:h2:D:/H2/db/lxz;MODE=Mysql;DB_CLOSE_DELAY=-1
    username: lxz
    password: 123456
    driver-class-name: org.h2.Driver

game:
  pool:
    configs:
      gobang:
        core-size: 2
        max-size: 10
        keep-alive-time: 10
      default:
        core-size: 2
        max-size: 10
        keep-alive-time: 10


# 应该要继承默认yml